hosts:
  production:
    hostname: dedi2835.your-server.de
    remote_user: transiti
    port: 222
    labels:
      stage: production
    deploy_path: '~/public_html/wp-content/themes'
    branch: master
    api_key: '48485499448090244f414ddfae8cb4183577a'
